# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: http://mazhuang.org/jekyll-theme-solid
date_format: "ordinal"
title: jekyll-theme-solid
author: Zhuang Ma 
paginate: 9

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet: 
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
pygments: true
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: mazhuang
changyan: false
